### PR TITLE
Finely tweaked kwinrc

### PR DESCRIPTION
**Pull request by es20490446e**
Maximizes usability, performance and visual integration of Deepin under Kwin.

The default theme right now is Breeze instead of Deepin, due to the following issues with the latest one:
- [Animations are slow](https://github.com/linuxdeepin/developer-center/issues/1259)
- [Windows are hard to resize](https://github.com/linuxdeepin/developer-center/issues/1178)

### CODE REVIEW

**Comment by es20490446e** [comment]
[Raw file](https://bin.privacytools.io/?3efbe7070645898c#cHm6EWbZRUSkZDknsFx6U8+uo8xyPn5j6KNE1jbzgM8=)

**Comment by zccrs** [comment]
I'm sorry, I can't accept these commit

**Comment by es20490446e** [comment]
What should be different for you to accept?

**Comment by es20490446e** [comment]
@zccrs @BLumia 

Also you can edit the commit if you wish, this is rather a base than a final file.

Just keep in mind that I have spend hours deciding on each detail, and everything is for a reason. I have also read all the configurations in the current kwinrc file, and integrated the ones that made sense.

You will rather want to try yourselves the new configuration, and ask in case of doubt, rather than assume that the decisions are random. I'm specialized in software usability.

**Comment by es20490446e** [comment]
@zccrs @BLumia If there's no reply in a week I will provide this file on its own package.

**Comment by BLumia** [comment]
> @zccrs @BLumia If there's no reply in a week I will provide this file on its own package.

Feel free to do that since you actually do not need an extra permission (as long as you followed the related licenses) to provide extra 3rd-party package.

btw, things related to UI/UX may always not easy to be changed without the designer and product manager's agreement. It's the main reason why Deepin does not accept PRs which affact the current UI/UX behavior.

**Comment by es20490446e** [comment]
@BLumia This kwinrc provides exactly the same design that does Deepin on Mutter.

The only visible change is that it sets Breeze as default theme, as a work around for the Deepin one having important bugs on Kwin.

But on the rest, the same behavior and the same look and feel. Even the same animations, and the same animation speed.

I opened this pull because that's not the case with the current kwinrc. The current file provides basic functionality. But apart from that it does nothing to follow the spec, it's just the default Kwin behaviour.

**Comment by BLumia** [comment]
> @BLumia This kwinrc provides exactly the same design that does Deepin on Mutter.
> 
> The only visible change is that it sets Breeze as default theme, as a work around for the Deepin one having important bugs on Kwin.
> 
> But on the rest, the same behavior and the same look and feel. Even the same animations, and the same animation speed.
> 
> I opened this pull because that's not the case with the current kwinrc. The current file provides basic functionality. But apart from that it does nothing to follow the spec, it's just the default Kwin behaviour.

cc @zccrs

**Comment by es20490446e** [comment]
[Proposed kwinrc](https://bin.privacytools.io/?d7451c88d74ff713#7LWulqcPPtAfQf7ljMyDNMFW6Rvtsso305PRDvlYdMc=).

**Comment by es20490446e** [comment]
Fork removed.

**Comment by aiamuzz** [comment]
> @BLumia This kwinrc provides exactly the same design that does Deepin on Mutter.
> 
> The only visible change is that it sets Breeze as default theme, as a work around for the Deepin one having important bugs on Kwin.
> 
> But on the rest, the same behavior and the same look and feel. Even the same animations, and the same animation speed.
> 
> I opened this pull because that's not the case with the current kwinrc. The current file provides basic functionality. But apart from that it does nothing to follow the spec, it's just the default Kwin behaviour.

@es20490446e ... Why don't you maintain it as your own fork on your github profile ... I would love to try your version ... just let me know how i can get it up and running on my Deepin OS !

**Comment by es20490446e** [comment]
Since the fork is gone, lets move the conversation to https://github.com/linuxdeepin/developer-center/issues/1232 for the moment.

**Pull request closed without merging**
